(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.AudioSystem=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const DEFAULTS={music:true,sfx:true,masterVolume:.7,musicVolume:.52,sfxVolume:.78,alwaysOnTop:true,reducedEffects:false,showDamage:true,autoUpdate:true,language:'pt-BR'};
function ensure(state){state.settings=Object.assign({},DEFAULTS,state.settings||{});for(const key of ['masterVolume','musicVolume','sfxVolume'])state.settings[key]=Math.max(0,Math.min(1,Number(state.settings[key])));return state.settings}
function create(){let context=null,master=null,musicGain=null,sfxGain=null,timer=null,drone=null,droneGain=null,step=0,settings={...DEFAULTS},lastSfx={};const melody=[45,48,52,50,43,47,50,55,45,48,57,52,43,50,47,40],bass=[33,33,31,31,29,29,28,28];
 function init(){if(context)return context;let AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AC)return null;context=new AC();master=context.createGain();musicGain=context.createGain();sfxGain=context.createGain();musicGain.connect(master);sfxGain.connect(master);master.connect(context.destination);apply(settings);return context}
 function tone(midi,duration=.24,type='triangle',gain=.06,target){if(!init())return;let now=context.currentTime,osc=context.createOscillator(),amp=context.createGain();osc.type=type;osc.frequency.value=440*Math.pow(2,(midi-69)/12);amp.gain.setValueAtTime(.0001,now);amp.gain.exponentialRampToValueAtTime(Math.max(.001,gain),now+.018);amp.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(amp);amp.connect(target||musicGain);osc.start(now);osc.stop(now+duration+.04)}
 function noise(duration=.08,gain=.035){if(!init())return;let length=Math.max(1,Math.floor(context.sampleRate*duration)),buffer=context.createBuffer(1,length,context.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);let source=context.createBufferSource(),amp=context.createGain(),now=context.currentTime;source.buffer=buffer;amp.gain.setValueAtTime(gain,now);amp.gain.exponentialRampToValueAtTime(.0001,now+duration);source.connect(amp);amp.connect(sfxGain);source.start(now)}
 function startDrone(){if(drone||!context)return;drone=context.createOscillator();droneGain=context.createGain();drone.type='sine';drone.frequency.value=55;droneGain.gain.value=.012;drone.connect(droneGain);droneGain.connect(musicGain);drone.start()}
 function stopDrone(){if(drone){try{drone.stop()}catch{}drone.disconnect();drone=null;droneGain=null}}
 function tick(){if(!settings.music||!context||context.state!=='running')return;tone(melody[step%melody.length],.34,step%4?'triangle':'sawtooth',.045);if(step%4===0)tone(bass[Math.floor(step/4)%bass.length],.68,'sine',.075);if(step%8===6)tone(69,.07,'square',.018);step++}
 async function start(next=settings){settings={...DEFAULTS,...next};let c=init();if(!c)return false;try{await c.resume()}catch{return false}apply(settings);if(settings.music){startDrone();if(!timer){tick();timer=setInterval(tick,340)}}return c.state==='running'}
 function stop(){if(timer){clearInterval(timer);timer=null}stopDrone();if(musicGain&&context)musicGain.gain.setTargetAtTime(0,context.currentTime,.05)}
 function apply(next){settings={...DEFAULTS,...next};if(!init())return;master.gain.setTargetAtTime(settings.masterVolume,context.currentTime,.025);musicGain.gain.setTargetAtTime(settings.music?settings.musicVolume:0,context.currentTime,.035);sfxGain.gain.setTargetAtTime(settings.sfx?settings.sfxVolume:0,context.currentTime,.025);if(settings.music&&context.state==='running'){startDrone();if(!timer){tick();timer=setInterval(tick,340)}}if(!settings.music)stop()}
 function sfx(kind='click'){if(!settings.sfx)return false;let now=Date.now(),minimum={shot:85,hit:70,click:35}[kind]||0;if(now-(lastSfx[kind]||0)<minimum)return false;lastSfx[kind]=now;let notes={click:[72,.055,'square',.028],equip:[64,.16,'triangle',.065],level:[60,.28,'sine',.075],error:[38,.22,'sawtooth',.06],boss:[34,.5,'square',.075],shot:[81,.055,'square',.035],hit:[43,.065,'triangle',.03],chest:[55,.18,'triangle',.07],mission:[67,.3,'sine',.075]},p=notes[kind]||notes.click;tone(p[0],p[1],p[2],p[3],sfxGain);if(['shot','hit','boss'].includes(kind))noise(kind==='boss'?.22:.045,kind==='boss'?.045:.018);if(kind==='chest'){setTimeout(()=>tone(62,.2,'triangle',.065,sfxGain),90);setTimeout(()=>tone(69,.28,'sine',.07,sfxGain),180)}return true}
 function snapshot(){return{supported:Boolean(globalThis.AudioContext||globalThis.webkitAudioContext),initialized:Boolean(context),state:context?.state||'idle',running:Boolean(timer&&context?.state==='running'),settings:{...settings}}}
 return{start,stop,apply,sfx,snapshot};
}
return{DEFAULTS,ensure,create};
});
