(() => {
const $=s=>document.querySelector(s), canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const stages=[{name:'Centro Infectado',file:'deadshift-city.png',tint:'#173c31'},{name:'Rodovia do Êxodo',file:'deadshift-highway.png',tint:'#493829'},{name:'Metrô Submerso',file:'deadshift-subway.png',tint:'#17333d'},{name:'Distrito em Chamas',file:'deadshift-cover.png',tint:'#4a281d'}];
const stageImages=Object.fromEntries(stages.map(s=>{let i=new Image();i.src=`../assets/${s.file}`;return[s.file,i]}));let worldScroll=0,abilityCooldowns={},buffs={},chestOpening=null,turretFlash=0;
const heroes=[
 {id:'maya',name:'Maya',role:'Batedora',icon:'⚡',color:'#e7a64d',level:1,xp:0,hp:110,maxHp:110,atk:12,rate:1.25,range:235,cost:0,skill:'Rajada'},
 {id:'bruno',name:'Bruno',role:'Brutamontes',icon:'🛡',color:'#64a9b7',level:1,xp:0,hp:180,maxHp:180,atk:17,rate:.72,range:85,cost:450,skill:'Impacto'},
 {id:'yuri',name:'Yuri',role:'Médico',icon:'✚',color:'#78c980',level:1,xp:0,hp:100,maxHp:100,atk:7,rate:.9,range:190,cost:900,skill:'Primeiros socorros'},
 {id:'iris',name:'Iris',role:'Incendiária',icon:'🔥',color:'#de7652',level:1,xp:0,hp:120,maxHp:120,atk:25,rate:.55,range:145,cost:1800,skill:'Coquetel molotov'}];
const defs={walker:{name:'Errante',hp:34,atk:5,speed:13,reward:7,color:'#729853'},runner:{name:'Corredor',hp:24,atk:7,speed:27,reward:10,color:'#a6a04c'},brute:{name:'Inchado',hp:115,atk:14,speed:8,reward:28,color:'#527d58'},spitter:{name:'Cuspidor',hp:55,atk:11,speed:10,reward:18,color:'#61b078'},boss:{name:'ABOMINAÇÃO',hp:750,atk:26,speed:6,reward:300,color:'#9f4e54'}};
const defaultState={version:3,scrap:80,cores:0,night:1,wave:1,baseHp:500,maxBaseHp:500,speed:1,paused:false,expanded:false,unlocked:['maya'],inventory:[],equipped:{},selectedHero:'maya',lootPity:0,heroProgress:{},skillPoints:{},heroTalents:{},expedition:{},expeditionPoints:0,chests:{field:1,military:0,outbreak:0},upgrades:{turret:0,walls:0,scavenger:0,medbay:0},kills:0,bosses:0,playtime:0,lastSeen:Date.now(),missions:{kill50:0,waves10:0,boss1:0},achievements:[]};
let S=load(), enemies=[],bullets=[],particles=[],spawnLeft=0,spawnTimer=0,waveCooldown=1,heroTimers={},last=performance.now(),autosave=0;
function load(){try{let raw=JSON.parse(localStorage.getItem('deadshift-save'))||{},s=Object.assign(structuredClone(defaultState),raw);s.upgrades=Object.assign({},defaultState.upgrades,raw.upgrades);s.missions=Object.assign({},defaultState.missions,raw.missions);s.equipped=raw.equipped||{};s.heroProgress=raw.heroProgress||{};s.inventory=(raw.inventory||[]).map(i=>i?.stats?i:LootSystem.generate({level:Math.max(1,(s.night||1)*3+(s.wave||1))}));s.version=3;return Progression.ensure(s)}catch{return Progression.ensure(structuredClone(defaultState))}}
heroes.forEach(h=>{let p=S.heroProgress[h.id];if(p)Object.assign(h,p);if(!S.equipped[h.id])S.equipped[h.id]={weapon:null,armor:null,charm:null}});
function save(){S.lastSeen=Date.now();heroes.forEach(h=>S.heroProgress[h.id]={level:h.level,xp:h.xp,hp:h.hp,maxHp:h.maxHp,atk:h.atk});localStorage.setItem('deadshift-save',JSON.stringify(S))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function activeHeroes(){return heroes.filter(h=>S.unlocked.includes(h.id))}
function heroGear(h){let ids=Object.values(S.equipped[h.id]||{});return ids.map(id=>S.inventory.find(i=>i.id===id)).filter(Boolean)}
function heroBonus(h){return LootSystem.total(heroGear(h))}
function heroTalent(h){return Progression.heroBonuses(S,h.id)}
function expeditionBonus(){return Progression.expeditionBonuses(S)}
function scaling(){return 1+(S.night-1)*.28+(S.wave-1)*.07}
function startWave(){if(enemies.length||spawnLeft)return;const boss=S.wave===10;spawnLeft=boss?1:Math.min(5+S.wave+S.night*2,28);spawnTimer=.2;if(boss)toast('⚠ ASSINATURA BIOLÓGICA ENORME DETECTADA');}
function spawn(){const boss=S.wave===10;let type=boss?'boss':S.night>2&&Math.random()<.14?'spitter':S.night>1&&Math.random()<.2?'brute':Math.random()<.28?'runner':'walker';let d=defs[type],mult=scaling();enemies.push({type,name:d.name,x:canvas.width+35,y:153+Math.random()*18,hp:d.hp*mult,maxHp:d.hp*mult,atk:d.atk*mult,speed:d.speed,reward:d.reward,hit:0,attack:0});spawnLeft--;}
function attack(hero,dt,idx){let bonus=heroBonus(hero),tal=heroTalent(hero),exp=expeditionBonus();heroTimers[hero.id]=(heroTimers[hero.id]||0)-dt;if(heroTimers[hero.id]>0)return;let hx=100+idx*54,target=enemies.filter(e=>e.x>hx&&e.x-hx<=hero.range).sort((a,b)=>a.x-b.x)[0];if(!target)return;let rate=(hero.rate+bonus.rate)*(1+(tal.rate||0)+(exp.speed||0)+(buffs.teamRate>0?.35:0)+(hero.id==='maya'&&buffs.mayaRate>0?1:0));heroTimers[hero.id]=1/rate;let crit=Math.random()<(.05+bonus.crit+(tal.crit||0)),damage=(hero.atk+bonus.attack)*(1+(hero.level-1)*.12)*(1+(tal.attack||0)+(exp.damage||0))*(1+Math.random()*.2)*(crit?1.8:1);if(crit)float('CRÍTICO!',target.x,target.y-42,'#ffd65a');if(hero.id==='iris'){enemies.filter(e=>Math.abs(e.x-target.x)<45).forEach(e=>hit(e,damage*.65,hero));}else bullets.push({x:hx+14,y:136-idx%2*8,tx:target,damage,hero,color:hero.color});}
function hit(e,d,h){d*=e.marked>0?1.4:1;e.hp-=d;e.hit=.1;float(Math.round(d),e.x,e.y-30,h.color);if(e.hp<=0){let scav=Number(heroBonus(h).scrap||0);S.scrap+=Math.round(e.reward*(1+S.upgrades.scavenger*.15+scav));S.kills++;S.missions.kill50++;if(Number.isFinite(h.xp)){h.xp+=10;if(h.xp>=h.level*100){h.xp-=h.level*100;h.level++;h.maxHp+=12;h.hp=h.maxHp;h.atk+=2;S.skillPoints[h.id]=(S.skillPoints[h.id]||0)+1;toast(`${h.name} nível ${h.level} · +1 ponto de habilidade`)}}S.lootPity++;let exp=expeditionBonus();if(e.type==='boss'||Math.random()<.085+(exp.chestRate||0)||S.lootPity>=12)loot(e.type==='boss');if(e.type==='boss'){let tier=exp.bossChest?'outbreak':S.night>3?'military':'field';S.chests[tier]++;S.expeditionPoints++;toast(`BAÚ ${tier.toUpperCase()} ENCONTRADO · +1 ponto de expedição`)}particles.push(...Array.from({length:8},()=>({x:e.x,y:e.y-8,vx:(Math.random()-.5)*55,vy:-Math.random()*45,life:.5,color:e.color})));enemies=enemies.filter(x=>x!==e)}}
function loot(boss=false){let item=LootSystem.generate({level:S.night*3+S.wave,pity:S.lootPity,boss});S.inventory.unshift(item);S.inventory=S.inventory.slice(0,60);if(['epic','legendary'].includes(item.rarity))S.lootPity=0;else S.lootPity=Math.max(0,S.lootPity-3);toast(`${item.rarityLabel.toUpperCase()}: ${item.name} · ${item.power} poder`)}
function useAbility(heroId,abilityId){let hero=heroes.find(h=>h.id===heroId),def=Progression.HEROES[heroId]?.abilities.find(a=>a.id===abilityId),key=`${heroId}:${abilityId}`;if(!hero||!def||abilityCooldowns[key]>0||!S.unlocked.includes(heroId))return;let cd=def.cooldown*(1-(heroTalent(hero).cooldown||0));abilityCooldowns[key]=cd;
 if(abilityId==='burst'){let t=enemies[0];if(t)for(let i=0;i<6;i++)setTimeout(()=>t?.hp>0&&hit(t,hero.atk*.75,hero),i*80)}
 if(abilityId==='dash')buffs.mayaRate=6;if(abilityId==='mark')enemies.forEach(e=>e.marked=7);
 if(abilityId==='taunt')buffs.guard=7;if(abilityId==='slam')enemies.filter(e=>e.x<430).forEach(e=>{e.stun=3;hit(e,hero.atk*1.4,hero)});if(abilityId==='fortify'){buffs.guard=10;S.baseHp=Math.min(S.maxBaseHp,S.baseHp+80)}
 if(abilityId==='heal'){let target=activeHeroes().sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(target){target.hp=Math.min(target.maxHp+heroBonus(target).hp,target.hp+70*(1+(heroTalent(hero).healing||0)));float('+CURA',120,115,'#8dff9b')}}if(abilityId==='stim')buffs.teamRate=8;if(abilityId==='revive')activeHeroes().forEach(h=>h.hp=Math.max(h.hp,(h.maxHp+heroBonus(h).hp)*.55));
 if(abilityId==='molotov')enemies.filter(e=>e.x<700).forEach(e=>e.burn=8);if(abilityId==='mine')enemies.slice(0,5).forEach(e=>{e.stun=2;e.slow=7;hit(e,hero.atk*1.6,hero)});if(abilityId==='inferno')enemies.forEach(e=>{e.burn=10;hit(e,hero.atk*2.1,hero)});
 toast(`${hero.name}: ${def.name}`);updateAbilityUI()}
function renderAbilities(){let bar=$('#ability-bar');bar.innerHTML=activeHeroes().map(h=>{let ability=Progression.HEROES[h.id].abilities[0];return `<button data-use-skill="${h.id}:${ability.id}" style="--hero:${h.color}"><span>${ability.icon}</span><small>${h.name}</small><i></i></button>`}).join('');bar.querySelectorAll('[data-use-skill]').forEach(b=>b.onclick=()=>{let [h,a]=b.dataset.useSkill.split(':');useAbility(h,a)});updateAbilityUI()}
function updateAbilityUI(){document.querySelectorAll('[data-use-skill]').forEach(b=>{let key=b.dataset.useSkill,cd=abilityCooldowns[key]||0,[h,a]=key.split(':'),max=Progression.HEROES[h].abilities.find(x=>x.id===a).cooldown;b.classList.toggle('cooldown',cd>0);b.querySelector('i').style.height=`${Math.min(100,cd/max*100)}%`;b.title=cd>0?`${cd.toFixed(1)}s`:'Pronto'})}
function float(t,x,y,c){let el=document.createElement('span');el.textContent=t;Object.assign(el.style,{position:'absolute',left:(x/canvas.width*100)+'%',top:(y/canvas.height*100)+'%',color:c,fontSize:'10px',fontWeight:'bold',textShadow:'1px 1px #000',transition:'1s',pointerEvents:'none'});$('#floaters').appendChild(el);requestAnimationFrame(()=>{el.style.transform='translateY(-25px)';el.style.opacity=0});setTimeout(()=>el.remove(),1000)}
function update(dt){if(S.paused)return;dt*=S.speed;S.playtime+=dt;worldScroll+=dt*(enemies.length?8:34);turretFlash=Math.max(0,turretFlash-dt);Object.keys(abilityCooldowns).forEach(k=>abilityCooldowns[k]=Math.max(0,abilityCooldowns[k]-dt));Object.keys(buffs).forEach(k=>buffs[k]=Math.max(0,buffs[k]-dt));S.maxBaseHp=Math.max(500,S.maxBaseHp);activeHeroes().forEach((h,i)=>attack(h,dt,i));if(enemies.length)activeHeroes().forEach(h=>Progression.HEROES[h.id].abilities.slice(1).forEach(a=>{if(!(abilityCooldowns[`${h.id}:${a.id}`]>0)&&Math.random()<dt*.18)useAbility(h.id,a.id)}));if(S.upgrades.medbay)activeHeroes().forEach(h=>h.hp=Math.min(h.maxHp+heroBonus(h).hp,h.hp+dt*S.upgrades.medbay*.7+(heroTalent(h).regen||0)*dt));if(S.upgrades.turret&&enemies[0]&&Math.random()<dt*S.upgrades.turret*.7){turretFlash=.14;hit(enemies[0],8*S.upgrades.turret,{id:'turret',color:'#9fdf42'})}
 if(spawnLeft){spawnTimer-=dt;if(spawnTimer<=0){spawn();spawnTimer=Math.max(.22,1-S.night*.04)}}else if(!enemies.length){waveCooldown-=dt;if(waveCooldown<=0){S.missions.waves10++;if(S.wave===10){S.bosses++;S.missions.boss1++;S.cores++;S.wave=1;S.night++;toast(`AMANHECER SOBREVIVIDO · NOITE ${S.night}`)}else S.wave++;waveCooldown=2;startWave();renderPanel()}}
 bullets.forEach(b=>{if(!b.tx||b.tx.hp<=0){b.dead=true;return}let dx=b.tx.x-b.x;b.x+=Math.sign(dx)*dt*520;if(Math.abs(dx)<15){hit(b.tx,b.damage,b.hero);b.dead=true}});bullets=bullets.filter(b=>!b.dead);
 enemies.forEach(e=>{e.hit=Math.max(0,e.hit-dt);e.attack-=dt;e.stun=Math.max(0,(e.stun||0)-dt);e.slow=Math.max(0,(e.slow||0)-dt);e.marked=Math.max(0,(e.marked||0)-dt);e.burn=Math.max(0,(e.burn||0)-dt);if(e.burn>0){e.burnTick=(e.burnTick||0)-dt;if(e.burnTick<=0){e.burnTick=.5;hit(e,4*scaling(),heroes[3])}}if(e.stun<=0&&e.x>65)e.x-=e.speed*(e.slow>0?.55:1)*dt;else if(e.x<=65&&e.attack<=0){let armor=(1-S.upgrades.walls*.07)*(buffs.guard>0?.5:1);S.baseHp-=e.atk*armor;e.attack=1.2;float('-'+Math.round(e.atk*armor),60,145,'#ff6d58');if(S.baseHp<=0)defeat()}});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);updateAbilityUI();checkAchievements();}
function defeat(){S.baseHp=S.maxBaseHp;S.wave=1;S.scrap=Math.floor(S.scrap*.85);enemies=[];spawnLeft=0;waveCooldown=3;toast('A BASE CAIU · 15% DA SUCATA FOI PERDIDA')}
function checkAchievements(){[['first',S.kills>=1,'Primeiro sangue'],['hundred',S.kills>=100,'Exterminador'],['boss',S.bosses>=1,'Quanto maior...'],['night5',S.night>=5,'Cinco noites']].forEach(([id,ok,n])=>{if(ok&&!S.achievements.includes(id)){S.achievements.push(id);toast(`CONQUISTA: ${n}`)}})}
function draw(){let w=canvas.width,h=canvas.height,stage=stages[Math.floor(((S.night-1)*10+S.wave-1)/3)%stages.length],bg=stageImages[stage.file];ctx.clearRect(0,0,w,h);ctx.fillStyle=stage.tint;ctx.fillRect(0,0,w,h);if(bg?.complete&&bg.naturalWidth){let off=worldScroll%w;ctx.globalAlpha=.72;ctx.drawImage(bg,-off,0,w,h);ctx.drawImage(bg,w-off,0,w,h);ctx.globalAlpha=1}else{ctx.fillStyle='#101a18';for(let i=0;i<16;i++)ctx.fillRect(i*78,30+(i%4)*13,65,120)}ctx.fillStyle='#17251ecc';ctx.fillRect(0,169,w,41);ctx.fillStyle='#71806f';for(let x=-(worldScroll%60);x<w;x+=60)ctx.fillRect(x,184,34,2);$('#stage-name').textContent=stage.name.toUpperCase();
 drawBase();
 activeHeroes().forEach((p,i)=>drawPerson(98+i*58,154,p.color,false,p.id));enemies.forEach(e=>drawZombie(e));bullets.forEach(b=>{ctx.fillStyle=b.color;ctx.shadowBlur=8;ctx.shadowColor=b.color;ctx.fillRect(b.x,b.y,7,3);ctx.shadowBlur=0});particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);ctx.globalAlpha=1});
 // HUD base
 ctx.fillStyle='#0b100ecc';ctx.fillRect(8,8,156,27);ctx.fillStyle='#27352e';ctx.fillRect(43,20,111,6);ctx.fillStyle=S.baseHp/S.maxBaseHp<.3?'#e55742':'#72bd57';ctx.fillRect(43,20,111*(S.baseHp/S.maxBaseHp),6);ctx.fillStyle='#d9e4dd';ctx.font='10px Consolas';ctx.fillText('BASE',15,19);ctx.fillStyle='#91a097';ctx.fillText(`${Math.ceil(S.baseHp)}/${S.maxBaseHp}`,43,16);
 let boss=enemies.find(e=>e.type==='boss');$('#bossbar').classList.toggle('hidden',!boss);if(boss){$('#bossname').textContent=boss.name;$('#bosshp').style.width=(100*boss.hp/boss.maxHp)+'%'}}
function rarityColor(r){return{common:'#b7c0ba',uncommon:'#71cf71',rare:'#65b8ff',epic:'#c383ff',legendary:'#ffb23e'}[r]||'#89968e'}
function drawBase(){let w=S.upgrades.walls,t=S.upgrades.turret,m=S.upgrades.medbay,s=S.upgrades.scavenger,fort=58+w*9;ctx.fillStyle='#161c18';ctx.fillRect(0,92,82,79);ctx.fillStyle=w?'#4b554b':'#49362c';ctx.fillRect(13,105,52,66);ctx.fillStyle=w>2?'#7b8375':'#626d60';ctx.fillRect(25,118,26,42);ctx.fillStyle='#172119';ctx.fillRect(30,126,16,34);ctx.fillStyle='#efad3d';ctx.fillRect(34,131,8,10);ctx.fillStyle='#242d27';ctx.fillRect(0,96,82,9);for(let i=0;i<=w;i++){let bx=55+i*8;ctx.fillStyle=i%2?'#6d5d49':'#514638';ctx.fillRect(bx,137,9,34);ctx.fillStyle='#9a805b';ctx.fillRect(bx+2,130,5,8);if(w>=3){ctx.fillStyle='#b0a78c';ctx.fillRect(bx+3,126,2,5)}}if(t){ctx.fillStyle='#39483f';ctx.fillRect(14,81-t*2,8,17+t*2);ctx.fillRect(9,79-t*2,19,5);ctx.fillStyle='#7e9185';ctx.fillRect(19,76-t*2,19+t*3,4);if(turretFlash){ctx.fillStyle='#fff7a8';ctx.fillRect(38+t*3,74-t*2,8,8);ctx.fillStyle='#ff9d2e';ctx.fillRect(46+t*3,76-t*2,7,4)}}if(m){ctx.fillStyle='#e8f2e9';ctx.fillRect(43,108,14,14);ctx.fillStyle='#4faf65';ctx.fillRect(48,110,4,10);ctx.fillRect(45,113,10,4);ctx.globalAlpha=.25+.15*Math.sin(S.playtime*4);ctx.strokeStyle='#70ff95';ctx.strokeRect(38-m*2,102-m*2,24+m*4,24+m*4);ctx.globalAlpha=1}if(s){for(let i=0;i<s;i++){ctx.fillStyle=['#7b5938','#4e694f','#706348'][i%3];ctx.fillRect(4+i*11,145-(i%2)*8,10,10);ctx.fillStyle='#b59a62';ctx.fillRect(6+i*11,147-(i%2)*8,6,2)}ctx.strokeStyle='#88a894';ctx.beginPath();ctx.moveTo(8,105);ctx.lineTo(8,84-s*2);ctx.stroke();ctx.fillStyle='#a8ef46';ctx.fillRect(6,82-s*2,4,4)}if(w||t||m||s){ctx.fillStyle='#0a100cbd';ctx.fillRect(4,105,8,45);ctx.fillStyle='#a8ef46';ctx.font='7px Consolas';ctx.fillText(`BASE NV ${w+t+m+s}`,3,164)}}
function drawPerson(x,y,c,zombie,id){let walking=!enemies.length,bob=Math.sin(S.playtime*(walking?10:6)+x)*2,step=Math.sin(S.playtime*12+x)>0?2:-2,h=heroes.find(v=>v.id===id),gear=h?heroGear(h):[],weapon=gear.find(i=>i.slot==='weapon'),armor=gear.find(i=>i.slot==='armor'),charm=gear.find(i=>i.slot==='charm');if(charm){ctx.globalAlpha=.18+.08*Math.sin(S.playtime*5);ctx.fillStyle=rarityColor(charm.rarity);ctx.beginPath();ctx.arc(x+6,y-6+bob,17,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=rarityColor(charm.rarity);ctx.fillRect(x-9+Math.sin(S.playtime*4)*4,y-9+bob,3,3)}ctx.fillStyle='#07100b88';ctx.fillRect(x-8,y+13,23,4);ctx.fillStyle=zombie?'#607d50':'#d0aa7c';ctx.fillRect(x,y-24+bob,13,13);ctx.fillStyle=armor?rarityColor(armor.rarity):c;ctx.fillRect(x-4-(armor?2:0),y-11+bob,21+(armor?4:0),19);if(armor){ctx.fillStyle='#dfe8e2';ctx.globalAlpha=.35;ctx.fillRect(x-2,y-8+bob,17,3);ctx.fillRect(x-5,y-5+bob,3,10);ctx.globalAlpha=1}ctx.fillStyle='#17221c';ctx.fillRect(x-1+step,y+8+bob,6,10);ctx.fillRect(x+10-step,y+8+bob,6,10);if(zombie){ctx.fillStyle='#b3e65e';ctx.fillRect(x+2,y-20+bob,2,2);ctx.fillRect(x+9,y-20+bob,2,2);ctx.fillStyle='#426442';ctx.fillRect(x+14,y-7+bob,8,4)}else{ctx.fillStyle='#222';ctx.fillRect(x+9,y-20+bob,2,2);if(id==='maya'){ctx.fillStyle='#df8b38';ctx.fillRect(x-3,y-28+bob,18,5)}if(id==='bruno'){ctx.fillStyle='#7db0bd';ctx.fillRect(x-4,y-27+bob,21,7);ctx.fillStyle='#405963';ctx.fillRect(x+14,y-11+bob,8,25)}if(id==='yuri'){ctx.fillStyle='#eef4e7';ctx.fillRect(x-4,y-9+bob,21,17);ctx.fillStyle='#57b86d';ctx.fillRect(x+3,y-5+bob,4,11);ctx.fillRect(x,y-2+bob,10,4)}if(id==='iris'){ctx.fillStyle='#8b58a3';ctx.fillRect(x-4,y-28+bob,20,6)}drawEquippedWeapon(x,y+bob,id,weapon)}}
function drawEquippedWeapon(x,y,id,item){let color=item?rarityColor(item.rarity):'#929d8f',name=(item?.base||item?.name||'').toLowerCase();ctx.fillStyle=color;if(name.includes('facão')||name.includes('machado')){ctx.fillRect(x+15,y-10,4,16);ctx.fillRect(x+18,y-13,3,8)}else if(name.includes('escopeta')){ctx.fillRect(x+14,y-8,23,6);ctx.fillStyle='#6a4a2f';ctx.fillRect(x+12,y-5,10,5)}else if(name.includes('carabina')||item?.slot==='weapon'){ctx.fillRect(x+14,y-8,20,4);ctx.fillRect(x+20,y-4,5,6)}else if(id==='maya'){ctx.fillRect(x+15,y-7,15,4)}else if(id==='iris'){ctx.fillStyle='#e56843';ctx.fillRect(x+15,y-7,17,5)}}
function drawZombie(e){ctx.save();if(e.hit)ctx.globalAlpha=.45;let scale=e.type==='boss'?2.1:e.type==='brute'?1.35:1;ctx.translate(e.x,e.y);ctx.scale(scale,scale);drawPerson(0,0,e.color,true);if(e.type==='spitter'){ctx.fillStyle='#78da48';ctx.fillRect(-5,-8,5,5)}ctx.restore();ctx.fillStyle='#281b19';ctx.fillRect(e.x-13*scale,e.y-34*scale,26*scale,3);ctx.fillStyle='#c34e3d';ctx.fillRect(e.x-13*scale,e.y-34*scale,26*scale*Math.max(0,e.hp/e.maxHp),3)}
function renderTop(){ $('#scrap').textContent=Math.floor(S.scrap).toLocaleString('pt-BR');$('#cores').textContent=S.cores;$('#night').textContent=S.night;$('#wave').textContent=S.wave;}
function statText(i){let labels={attack:'ATQ',hp:'VIDA',rate:'VEL',crit:'CRÍT',scrap:'SUCATA'};return Object.entries(i.stats||{}).filter(([,v])=>v).map(([k,v])=>`${labels[k]} +${k==='rate'||k==='crit'||k==='scrap'?Math.round(v*100)+'%':Math.round(v)}`).join(' · ')}
function enhanceGearCards(){document.querySelectorAll('.hero-card').forEach((card,index)=>{let gear=heroGear(heroes[index]),row=card.querySelector('.gear-row');if(!row)return;let box=document.createElement('div');box.className='equipped-list';box.innerHTML=gear.length?gear.map(i=>`<span><i class="${i.rarity}">${i.icon}</i><b class="${i.rarity}">${i.name}</b><small>${statText(i)}</small></span>`).join(''):'<em>Nenhum equipamento visual equipado</em>';row.after(box)})}
function renderPanel(tab=document.querySelector('nav .active')?.dataset.tab||'squad'){let p=$('#panel');if(tab==='squad')p.innerHTML=`<div class="panel-head"><div><h2>ESQUADRÃO</h2><p class="subtitle">Sobreviventes ativos e equipamento de campo</p></div></div><div class="grid">${heroes.map(h=>{let b=heroBonus(h),gear=heroGear(h);return `<article class="card hero-card ${S.unlocked.includes(h.id)?'selected':''}" style="--hero:${h.color}"><div class="portrait">${h.icon}<span>${h.level}</span></div><strong>${h.name}</strong><div class="meta">${h.role} · NV ${h.level}</div><div class="hp"><i style="width:${100*h.hp/(h.maxHp+b.hp)}%"></i></div><div class="stats"><span>⚔ ${Math.round((h.atk+b.attack)*(1+(h.level-1)*.12))}</span><span>♥ ${Math.round(h.maxHp+b.hp)}</span><span>◷ ${(h.rate+b.rate).toFixed(2)}</span></div><div class="gear-row">${['weapon','armor','charm'].map(s=>{let i=gear.find(x=>x.slot===s);return `<span class="gear-slot ${i?i.rarity:''}" title="${i?.name||'Slot vazio'}">${i?.icon||'·'}</span>`}).join('')}</div>${S.unlocked.includes(h.id)?`<button class="action" data-level="${h.id}">TREINAR · ${h.level*90} ☣</button>`:`<button class="action" data-unlock="${h.id}" ${S.scrap<h.cost?'disabled':''}>RECRUTAR · ${h.cost} ☣</button>`}</article>`}).join('')}</div>`;
else if(tab==='skills'){let selected=heroes.find(h=>h.id===S.selectedHero)||heroes[0],def=Progression.HEROES[selected.id];p.innerHTML=`<div class="panel-head"><div><h2>HABILIDADES</h2><p class="subtitle">${def.identity} · ${S.skillPoints[selected.id]||0} pontos disponíveis</p></div><div class="survivor-select">${activeHeroes().map(h=>`<button data-select-skill-hero="${h.id}" class="${selected.id===h.id?'on':''}">${h.icon} ${h.name}</button>`).join('')}</div></div><div class="skill-layout"><div class="active-skills">${def.abilities.map((a,i)=>`<article class="skill-card"><span>${a.icon}</span><div><b>${a.name}</b><small>${a.desc}</small><em>${a.cooldown}s · ${i===0?'EQUIPADA NA BARRA':'PASSIVA AUTOMÁTICA'}</em></div></article>`).join('')}</div><div class="talent-tree">${def.tree.map(([id,name,stat,value],i)=>{let rank=S.heroTalents[selected.id][id]||0,cost=rank+1;return `<div class="talent-node ${rank?'learned':''}" style="--x:${(i%2)*140}px"><i>${i+1}</i><div><b>${name}</b><small>${stat.toUpperCase()} +${Math.round(value*100)}% por nível</small><em>NÍVEL ${rank}/5</em></div><button data-buy-talent="${selected.id}:${id}" ${rank>=5||S.skillPoints[selected.id]<cost?'disabled':''}>+ ${cost} PT</button></div>`}).join('')}</div></div>`}
else if(tab==='expedition'){p.innerHTML=`<div class="panel-head"><div><h2>ÁRVORE DE EXPEDIÇÃO</h2><p class="subtitle">Rotas permanentes para baús, dano e velocidade · ${S.expeditionPoints} pontos</p></div></div><div class="expedition-tree">${Progression.EXPEDITION.map(([id,name,desc,base],i)=>{let rank=S.expedition[id]||0,cost=base+rank;return `<article class="exp-node ${rank?'learned':''}"><span>${['▧','◇','⚔','»','◷','◆','☣'][i]}</span><b>${name}</b><small>${desc}</small><em>NÍVEL ${rank}/5</em><button data-buy-exp="${id}" ${rank>=5||S.expeditionPoints<cost?'disabled':''}>DESBLOQUEAR · ${cost}</button></article>`}).join('')}</div>`}
else if(tab==='chests'){p.innerHTML=`<div class="panel-head"><div><h2>COFRE DA QUARENTENA</h2><p class="subtitle">Abra baús encontrados em chefes e expedições</p></div></div><div class="chest-room">${[['field','Baú de Campo','Equipamento comum a raro','▤'],['military','Caixa Militar','Equipamento raro a épico','▥'],['outbreak','Cofre do Surto','Épico ou lendário garantido','▦']].map(([id,n,d,icon])=>`<article class="chest ${id}"><span>${icon}</span><h3>${n}</h3><p>${d}</p><b>${S.chests[id]} disponíveis</b><button data-open-chest="${id}" ${!S.chests[id]?'disabled':''}>ABRIR BAÚ</button></article>`).join('')}</div><div id="chest-result"></div>`}
else if(tab==='arsenal'){let selected=heroes.find(h=>h.id===S.selectedHero)||heroes[0],equippedIds=Object.values(S.equipped[selected.id]||{});p.innerHTML=`<div class="panel-head"><div><h2>ARSENAL</h2><p class="subtitle">${S.inventory.length}/60 itens · ${LootSystem.chanceLabel(S.lootPity)}</p></div><div class="survivor-select">${activeHeroes().map(h=>`<button data-select-hero="${h.id}" class="${selected.id===h.id?'on':''}">${h.icon} ${h.name}</button>`).join('')}</div></div><div class="loadout"><div><small>ARMA</small><b>${S.equipped[selected.id].weapon?'EQUIPADA':'VAZIA'}</b></div><div><small>PROTEÇÃO</small><b>${S.equipped[selected.id].armor?'EQUIPADA':'VAZIA'}</b></div><div><small>AMULETO</small><b>${S.equipped[selected.id].charm?'EQUIPADO':'VAZIO'}</b></div></div><div class="inventory">${S.inventory.length?S.inventory.map(i=>`<article class="item rarity-${i.rarity}"><span class="item-icon ${i.rarity}">${i.icon}</span><span class="item-info"><strong class="${i.rarity}">${i.name}</strong><em>${i.rarityLabel} · NV ${i.level} · QUALIDADE ${i.quality}%</em><small>${statText(i)}</small></span><span class="power"><b>${i.power}</b><small>PODER</small></span><div class="item-actions"><button class="action" data-equip="${i.id}">${equippedIds.includes(i.id)?'REMOVER':'EQUIPAR'}</button><button class="recycle" data-scrap="${i.id}" ${equippedIds.includes(i.id)?'disabled':''}>♻ ${i.salvage}</button></div></article>`).join(''):'<div class="empty-loot"><b>ARSENAL VAZIO</b><p>Infectados têm chance de derrubar equipamento. Um item é garantido após 12 eliminações sem saque.</p></div>'}</div>`}
else if(tab==='base')p.innerHTML=`<h2>ABRIGO 13</h2><div class="two-col"><div>${[['walls','Fortificações','Reduz o dano à base'],['turret','Torre automática','Dispara contra infectados'],['scavenger','Equipe de coleta','Aumenta a sucata recebida'],['medbay','Enfermaria','Regenera os sobreviventes']].map(([id,n,d])=>`<div class="mission"><h3>${n} · NV ${S.upgrades[id]}</h3><p>${d}</p><button class="action" data-upgrade="${id}">MELHORAR · ${(S.upgrades[id]+1)*350} ☣</button></div>`).join('')}</div><div><h3>INTEGRIDADE DO ABRIGO</h3><div class="bar"><i style="width:${100*S.baseHp/S.maxBaseHp}%"></i></div><p class="meta">${Math.ceil(S.baseHp)} / ${S.maxBaseHp}</p><button class="action" data-repair>REPARAR · ${Math.ceil((S.maxBaseHp-S.baseHp)*.25)} ☣</button></div></div>`;
else if(tab==='missions')p.innerHTML=`<h2>MISSÕES</h2>${[['kill50','Limpeza urbana',S.missions.kill50,50,150],['waves10','Aguente firme',S.missions.waves10,10,200],['boss1','Caça grande',S.missions.boss1,1,1]].map(([id,n,v,max,reward])=>`<div class="mission ${v>=max?'complete':''}"><h3>${n}</h3><div class="bar"><i style="width:${Math.min(100,v/max*100)}%"></i></div><p>${Math.min(v,max)} / ${max} · Recompensa: ${id==='boss1'?'1 ◆':reward+' ☣'}</p>${v>=max?`<button class="action" data-claim="${id}" data-reward="${reward}">RESGATAR</button>`:''}</div>`).join('')}`;
else p.innerHTML=`<h2>ARQUIVO DA QUARENTENA</h2><div class="two-col"><div><h3>ESTATÍSTICAS</h3><p>Infectados eliminados: <b>${S.kills}</b></p><p>Abominações abatidas: <b>${S.bosses}</b></p><p>Noite máxima: <b>${S.night}</b></p><p>Tempo em campo: <b>${Math.floor(S.playtime/60)} min</b></p></div><div><h3>CONQUISTAS (${S.achievements.length}/4)</h3>${['first','hundred','boss','night5'].map((id,i)=>`<p style="opacity:${S.achievements.includes(id)?1:.25}">☣ ${['Primeiro sangue','Exterminador','Quanto maior...','Cinco noites'][i]}</p>`).join('')}</div></div>`;bindPanel();enhanceGearCards()}
function openChest(tier){if(!S.chests[tier])return;S.chests[tier]--;let amount=tier==='outbreak'?4:tier==='military'?3:2,items=[];for(let n=0;n<amount;n++){let item=LootSystem.generate({level:S.night*3+S.wave,pity:tier==='military'?10:0,boss:tier==='outbreak'});S.inventory.unshift(item);items.push(item)}S.inventory=S.inventory.slice(0,60);renderPanel('chests');let result=$('#chest-result');result.innerHTML=`<div class="chest-reveal"><h3>CONTEÚDO RECUPERADO</h3>${items.map((i,n)=>`<div class="reveal-item rarity-${i.rarity}" style="animation-delay:${n*.16}s"><span>${i.icon}</span><b class="${i.rarity}">${i.name}</b><small>${i.power} poder · ${i.rarityLabel}</small></div>`).join('')}</div>`;toast(`${amount} itens adicionados ao arsenal`)}
function bindPanel(){document.querySelectorAll('[data-unlock]').forEach(b=>b.onclick=()=>{let h=heroes.find(x=>x.id===b.dataset.unlock);if(S.scrap>=h.cost){S.scrap-=h.cost;S.unlocked.push(h.id);S.selectedHero=h.id;renderAbilities();toast(`${h.name} entrou no esquadrão`);renderPanel()}});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{let h=heroes.find(x=>x.id===b.dataset.level),c=h.level*90;if(S.scrap>=c){S.scrap-=c;h.level++;h.atk+=2;h.maxHp+=12;h.hp=h.maxHp;S.skillPoints[h.id]=(S.skillPoints[h.id]||0)+1;renderPanel()}});document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{let id=b.dataset.upgrade,c=(S.upgrades[id]+1)*350;if(S.scrap>=c){S.scrap-=c;S.upgrades[id]++;if(id==='walls'){S.maxBaseHp+=100;S.baseHp+=100}renderPanel()}});document.querySelectorAll('[data-select-hero]').forEach(b=>b.onclick=()=>{S.selectedHero=b.dataset.selectHero;renderPanel('arsenal')});document.querySelectorAll('[data-select-skill-hero]').forEach(b=>b.onclick=()=>{S.selectedHero=b.dataset.selectSkillHero;renderPanel('skills')});document.querySelectorAll('[data-buy-talent]').forEach(b=>b.onclick=()=>{let [h,n]=b.dataset.buyTalent.split(':');if(Progression.buyHero(S,h,n)){toast('Talento aprimorado');renderPanel('skills')}});document.querySelectorAll('[data-buy-exp]').forEach(b=>b.onclick=()=>{if(Progression.buyExpedition(S,b.dataset.buyExp)){toast('Rota de expedição desbloqueada');renderPanel('expedition')}});document.querySelectorAll('[data-open-chest]').forEach(b=>b.onclick=()=>openChest(b.dataset.openChest));document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{let item=S.inventory.find(i=>i.id===b.dataset.equip),set=S.equipped[S.selectedHero];if(!item||!set)return;if(set[item.slot]===item.id){set[item.slot]=null;toast(`${item.name} removido`)}else{set[item.slot]=item.id;toast(`${item.name} equipado`)}renderPanel('arsenal')});document.querySelectorAll('[data-scrap]').forEach(b=>b.onclick=()=>{let i=S.inventory.find(x=>String(x.id)===b.dataset.scrap);if(!i||Object.values(S.equipped).some(set=>Object.values(set).includes(i.id)))return;S.scrap+=Number(i.salvage||8);S.inventory=S.inventory.filter(x=>x!==i);toast(`Item reciclado · +${i.salvage||8} sucata`);renderPanel('arsenal')});document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{let id=b.dataset.claim;if(id==='boss1')S.cores++;else S.scrap+=+b.dataset.reward;S.missions[id]=0;renderPanel()});let r=document.querySelector('[data-repair]');if(r)r.onclick=()=>{let c=Math.ceil((S.maxBaseHp-S.baseHp)*.25);if(S.scrap>=c){S.scrap-=c;S.baseHp=S.maxBaseHp;renderPanel()}}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPanel(b.dataset.tab)});$('#expand').onclick=()=>{S.expanded=!S.expanded;document.body.className=S.expanded?'expanded':'compact';window.desktop?.mode(S.expanded?'expanded':'compact');$('#expand').textContent=S.expanded?'▾':'▣';if(S.expanded)renderPanel()};$('#pause').onclick=()=>{S.paused=!S.paused;$('#pause').textContent=S.paused?'▶':'Ⅱ'};$('#speed').onclick=()=>{S.speed=S.speed===1?2:S.speed===2?3:1;$('#speed').textContent=S.speed+'×'};$('#minimize').onclick=()=>window.desktop?.minimize();$('#close').onclick=()=>{save();window.desktop?.close()};
let away=Math.min(8*3600,Math.max(0,(Date.now()-S.lastSeen)/1000));if(away>60){let gain=Math.floor(away/10*(4+S.night)*(1+(expeditionBonus().offline||0)));S.scrap+=gain;setTimeout(()=>toast(`Coleta offline: +${gain} sucata`),800)}
window.__seedVisualTest=()=>{window.__visualTestActive=true;S.upgrades={walls:4,turret:3,scavenger:3,medbay:3};S.unlocked=heroes.map(h=>h.id);for(const h of heroes){for(const slot of ['weapon','armor','charm']){let item;do{item=LootSystem.generate({level:18,pity:12,boss:true})}while(item.slot!==slot);S.inventory.unshift(item);S.equipped[h.id][slot]=item.id}}renderAbilities();renderPanel('squad')};
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;update(dt);draw();renderTop();autosave+=dt;if(autosave>10&&!window.__visualTestActive){save();autosave=0}requestAnimationFrame(loop)}startWave();renderPanel();renderAbilities();requestAnimationFrame(loop);window.addEventListener('beforeunload',()=>{if(!window.__visualTestActive)save()});
})();
