(() => {
const $=s=>document.querySelector(s), canvas=$('#game'),ctx=canvas.getContext('2d'),bgImage=new Image();ctx.imageSmoothingEnabled=false;bgImage.src='../assets/deadshift-city.png';
const heroes=[
 {id:'maya',name:'Maya',role:'Batedora',icon:'⚡',color:'#e7a64d',level:1,xp:0,hp:110,maxHp:110,atk:12,rate:1.25,range:235,cost:0,skill:'Rajada'},
 {id:'bruno',name:'Bruno',role:'Brutamontes',icon:'🛡',color:'#64a9b7',level:1,xp:0,hp:180,maxHp:180,atk:17,rate:.72,range:85,cost:450,skill:'Impacto'},
 {id:'yuri',name:'Yuri',role:'Médico',icon:'✚',color:'#78c980',level:1,xp:0,hp:100,maxHp:100,atk:7,rate:.9,range:190,cost:900,skill:'Primeiros socorros'},
 {id:'iris',name:'Iris',role:'Incendiária',icon:'🔥',color:'#de7652',level:1,xp:0,hp:120,maxHp:120,atk:25,rate:.55,range:145,cost:1800,skill:'Coquetel molotov'}];
const defs={walker:{name:'Errante',hp:34,atk:5,speed:13,reward:7,color:'#729853'},runner:{name:'Corredor',hp:24,atk:7,speed:27,reward:10,color:'#a6a04c'},brute:{name:'Inchado',hp:115,atk:14,speed:8,reward:28,color:'#527d58'},spitter:{name:'Cuspidor',hp:55,atk:11,speed:10,reward:18,color:'#61b078'},boss:{name:'ABOMINAÇÃO',hp:750,atk:26,speed:6,reward:300,color:'#9f4e54'}};
const defaultState={version:2,scrap:80,cores:0,night:1,wave:1,baseHp:500,maxBaseHp:500,speed:1,paused:false,expanded:false,unlocked:['maya'],inventory:[],equipped:{},selectedHero:'maya',lootPity:0,heroProgress:{},upgrades:{turret:0,walls:0,scavenger:0,medbay:0},kills:0,bosses:0,playtime:0,lastSeen:Date.now(),missions:{kill50:0,waves10:0,boss1:0},achievements:[]};
let S=load(), enemies=[],bullets=[],particles=[],spawnLeft=0,spawnTimer=0,waveCooldown=1,heroTimers={},last=performance.now(),autosave=0;
function load(){try{let raw=JSON.parse(localStorage.getItem('deadshift-save'))||{},s=Object.assign(structuredClone(defaultState),raw);s.upgrades=Object.assign({},defaultState.upgrades,raw.upgrades);s.missions=Object.assign({},defaultState.missions,raw.missions);s.equipped=raw.equipped||{};s.heroProgress=raw.heroProgress||{};s.inventory=(raw.inventory||[]).map(i=>i?.stats?i:LootSystem.generate({level:Math.max(1,(s.night||1)*3+(s.wave||1))}));s.version=2;return s}catch{return structuredClone(defaultState)}}
heroes.forEach(h=>{let p=S.heroProgress[h.id];if(p)Object.assign(h,p);if(!S.equipped[h.id])S.equipped[h.id]={weapon:null,armor:null,charm:null}});
function save(){S.lastSeen=Date.now();heroes.forEach(h=>S.heroProgress[h.id]={level:h.level,xp:h.xp,hp:h.hp,maxHp:h.maxHp,atk:h.atk});localStorage.setItem('deadshift-save',JSON.stringify(S))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function activeHeroes(){return heroes.filter(h=>S.unlocked.includes(h.id))}
function heroGear(h){let ids=Object.values(S.equipped[h.id]||{});return ids.map(id=>S.inventory.find(i=>i.id===id)).filter(Boolean)}
function heroBonus(h){return LootSystem.total(heroGear(h))}
function scaling(){return 1+(S.night-1)*.28+(S.wave-1)*.07}
function startWave(){if(enemies.length||spawnLeft)return;const boss=S.wave===10;spawnLeft=boss?1:Math.min(5+S.wave+S.night*2,28);spawnTimer=.2;if(boss)toast('⚠ ASSINATURA BIOLÓGICA ENORME DETECTADA');}
function spawn(){const boss=S.wave===10;let type=boss?'boss':S.night>2&&Math.random()<.14?'spitter':S.night>1&&Math.random()<.2?'brute':Math.random()<.28?'runner':'walker';let d=defs[type],mult=scaling();enemies.push({type,name:d.name,x:canvas.width+35,y:153+Math.random()*18,hp:d.hp*mult,maxHp:d.hp*mult,atk:d.atk*mult,speed:d.speed,reward:d.reward,hit:0,attack:0});spawnLeft--;}
function attack(hero,dt,idx){let bonus=heroBonus(hero);heroTimers[hero.id]=(heroTimers[hero.id]||0)-dt;if(heroTimers[hero.id]>0)return;let hx=100+idx*54,target=enemies.filter(e=>e.x>hx&&e.x-hx<=hero.range).sort((a,b)=>a.x-b.x)[0];if(!target)return;heroTimers[hero.id]=1/(hero.rate+bonus.rate);let crit=Math.random()<(.05+bonus.crit),damage=(hero.atk+bonus.attack)*(1+(hero.level-1)*.12)*(1+Math.random()*.2)*(crit?1.8:1);if(crit)float('CRÍTICO!',target.x,target.y-42,'#ffd65a');if(hero.id==='iris'){enemies.filter(e=>Math.abs(e.x-target.x)<45).forEach(e=>hit(e,damage*.65,hero));}else bullets.push({x:hx+14,y:136-idx%2*8,tx:target,damage,hero,color:hero.color});}
function hit(e,d,h){e.hp-=d;e.hit=.1;float(Math.round(d),e.x,e.y-30,h.color);if(e.hp<=0){let scav=Number(heroBonus(h).scrap||0);S.scrap+=Math.round(e.reward*(1+S.upgrades.scavenger*.15+scav));S.kills++;S.missions.kill50++;if(Number.isFinite(h.xp)){h.xp+=10;if(h.xp>=h.level*100){h.xp-=h.level*100;h.level++;h.maxHp+=12;h.hp=h.maxHp;h.atk+=2;toast(`${h.name} alcançou o nível ${h.level}`)}}S.lootPity++;if(e.type==='boss'||Math.random()<.085||S.lootPity>=12)loot(e.type==='boss');particles.push(...Array.from({length:8},()=>({x:e.x,y:e.y-8,vx:(Math.random()-.5)*55,vy:-Math.random()*45,life:.5,color:e.color})));enemies=enemies.filter(x=>x!==e)}}
function loot(boss=false){let item=LootSystem.generate({level:S.night*3+S.wave,pity:S.lootPity,boss});S.inventory.unshift(item);S.inventory=S.inventory.slice(0,60);if(['epic','legendary'].includes(item.rarity))S.lootPity=0;else S.lootPity=Math.max(0,S.lootPity-3);toast(`${item.rarityLabel.toUpperCase()}: ${item.name} · ${item.power} poder`)}
function float(t,x,y,c){let el=document.createElement('span');el.textContent=t;Object.assign(el.style,{position:'absolute',left:(x/canvas.width*100)+'%',top:(y/canvas.height*100)+'%',color:c,fontSize:'10px',fontWeight:'bold',textShadow:'1px 1px #000',transition:'1s',pointerEvents:'none'});$('#floaters').appendChild(el);requestAnimationFrame(()=>{el.style.transform='translateY(-25px)';el.style.opacity=0});setTimeout(()=>el.remove(),1000)}
function update(dt){if(S.paused)return;dt*=S.speed;S.playtime+=dt;S.maxBaseHp=Math.max(500,S.maxBaseHp);activeHeroes().forEach((h,i)=>attack(h,dt,i));if(S.upgrades.medbay)activeHeroes().forEach(h=>h.hp=Math.min(h.maxHp+heroBonus(h).hp,h.hp+dt*S.upgrades.medbay*.7));if(S.upgrades.turret&&enemies[0]&&Math.random()<dt*S.upgrades.turret*.7)hit(enemies[0],8*S.upgrades.turret,{id:'turret',color:'#9fdf42'});
 if(spawnLeft){spawnTimer-=dt;if(spawnTimer<=0){spawn();spawnTimer=Math.max(.22,1-S.night*.04)}}else if(!enemies.length){waveCooldown-=dt;if(waveCooldown<=0){S.missions.waves10++;if(S.wave===10){S.bosses++;S.missions.boss1++;S.cores++;S.wave=1;S.night++;toast(`AMANHECER SOBREVIVIDO · NOITE ${S.night}`)}else S.wave++;waveCooldown=2;startWave();renderPanel()}}
 bullets.forEach(b=>{if(!b.tx||b.tx.hp<=0){b.dead=true;return}let dx=b.tx.x-b.x;b.x+=Math.sign(dx)*dt*520;if(Math.abs(dx)<15){hit(b.tx,b.damage,b.hero);b.dead=true}});bullets=bullets.filter(b=>!b.dead);
 enemies.forEach(e=>{e.hit=Math.max(0,e.hit-dt);e.attack-=dt;if(e.x>65)e.x-=e.speed*dt;else if(e.attack<=0){let armor=1-S.upgrades.walls*.07;S.baseHp-=e.atk*armor;e.attack=1.2;float('-'+Math.round(e.atk*armor),60,145,'#ff6d58');if(S.baseHp<=0)defeat()}});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=80*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);checkAchievements();}
function defeat(){S.baseHp=S.maxBaseHp;S.wave=1;S.scrap=Math.floor(S.scrap*.85);enemies=[];spawnLeft=0;waveCooldown=3;toast('A BASE CAIU · 15% DA SUCATA FOI PERDIDA')}
function checkAchievements(){[['first',S.kills>=1,'Primeiro sangue'],['hundred',S.kills>=100,'Exterminador'],['boss',S.bosses>=1,'Quanto maior...'],['night5',S.night>=5,'Cinco noites']].forEach(([id,ok,n])=>{if(ok&&!S.achievements.includes(id)){S.achievements.push(id);toast(`CONQUISTA: ${n}`)}})}
function draw(){let w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);let grd=ctx.createLinearGradient(0,0,0,h);grd.addColorStop(0,'#172b29');grd.addColorStop(.65,'#18231e');grd.addColorStop(1,'#0b100e');ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);if(bgImage.complete){ctx.globalAlpha=.56;ctx.drawImage(bgImage,0,0,w,h);ctx.globalAlpha=1} // skyline
 if(!bgImage.complete){ctx.fillStyle='#101a18';for(let i=0;i<16;i++){let x=i*78+(i%3)*8,hh=45+(i*19)%55;ctx.fillRect(x,78-hh,65,hh);ctx.fillStyle='#52673a';for(let yy=90-hh;yy<70;yy+=17)if((i+yy)%3)ctx.fillRect(x+10,yy,5,5);ctx.fillStyle='#101a18'}}ctx.fillStyle='#25332bcc';ctx.fillRect(0,169,w,41);ctx.fillStyle='#71806f';for(let x=0;x<w;x+=60)ctx.fillRect(x,184,34,2);
 // base
 ctx.fillStyle='#49362c';ctx.fillRect(18,105,48,66);ctx.fillStyle='#78826a';ctx.fillRect(28,117,27,43);ctx.fillStyle='#9fdf42';ctx.fillRect(36,126,11,5);ctx.fillStyle='#18231d';ctx.fillRect(0,99,72,8);ctx.fillStyle='#77b147';ctx.fillRect(8,93,9,6);
 activeHeroes().forEach((p,i)=>drawPerson(98+i*54,154,p.color,false,p.icon));enemies.forEach(e=>drawZombie(e));bullets.forEach(b=>{ctx.fillStyle=b.color;ctx.fillRect(b.x,b.y,5,2)});particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);ctx.globalAlpha=1});
 // HUD base
 ctx.fillStyle='#0b100ecc';ctx.fillRect(8,8,156,27);ctx.fillStyle='#27352e';ctx.fillRect(43,20,111,6);ctx.fillStyle=S.baseHp/S.maxBaseHp<.3?'#e55742':'#72bd57';ctx.fillRect(43,20,111*(S.baseHp/S.maxBaseHp),6);ctx.fillStyle='#d9e4dd';ctx.font='10px Consolas';ctx.fillText('BASE',15,19);ctx.fillStyle='#91a097';ctx.fillText(`${Math.ceil(S.baseHp)}/${S.maxBaseHp}`,43,16);
 let boss=enemies.find(e=>e.type==='boss');$('#bossbar').classList.toggle('hidden',!boss);if(boss){$('#bossname').textContent=boss.name;$('#bosshp').style.width=(100*boss.hp/boss.maxHp)+'%'}}
function drawPerson(x,y,c,zombie,icon){let bob=Math.sin(S.playtime*6+x)*2;ctx.fillStyle='#151b17';ctx.fillRect(x-7,y+12,20,4);ctx.fillStyle=zombie?'#607d50':'#d0aa7c';ctx.fillRect(x,y-22+bob,12,12);ctx.fillStyle=c;ctx.fillRect(x-3,y-10+bob,18,18);ctx.fillStyle='#17221c';ctx.fillRect(x-1,y+8+bob,6,9);ctx.fillRect(x+9,y+8+bob,6,9);if(zombie){ctx.fillStyle='#b3e65e';ctx.fillRect(x+2,y-18+bob,2,2);ctx.fillRect(x+8,y-18+bob,2,2)}else{ctx.fillStyle='#222';ctx.fillRect(x+8,y-18+bob,2,2)}}
function drawZombie(e){ctx.save();if(e.hit)ctx.globalAlpha=.45;let scale=e.type==='boss'?2.1:e.type==='brute'?1.35:1;ctx.translate(e.x,e.y);ctx.scale(scale,scale);drawPerson(0,0,e.color,true);if(e.type==='spitter'){ctx.fillStyle='#78da48';ctx.fillRect(-5,-8,5,5)}ctx.restore();ctx.fillStyle='#281b19';ctx.fillRect(e.x-13*scale,e.y-34*scale,26*scale,3);ctx.fillStyle='#c34e3d';ctx.fillRect(e.x-13*scale,e.y-34*scale,26*scale*Math.max(0,e.hp/e.maxHp),3)}
function renderTop(){ $('#scrap').textContent=Math.floor(S.scrap).toLocaleString('pt-BR');$('#cores').textContent=S.cores;$('#night').textContent=S.night;$('#wave').textContent=S.wave;}
function statText(i){let labels={attack:'ATQ',hp:'VIDA',rate:'VEL',crit:'CRÍT',scrap:'SUCATA'};return Object.entries(i.stats||{}).filter(([,v])=>v).map(([k,v])=>`${labels[k]} +${k==='rate'||k==='crit'||k==='scrap'?Math.round(v*100)+'%':Math.round(v)}`).join(' · ')}
function renderPanel(tab=document.querySelector('nav .active')?.dataset.tab||'squad'){let p=$('#panel');if(tab==='squad')p.innerHTML=`<div class="panel-head"><div><h2>ESQUADRÃO</h2><p class="subtitle">Sobreviventes ativos e equipamento de campo</p></div></div><div class="grid">${heroes.map(h=>{let b=heroBonus(h),gear=heroGear(h);return `<article class="card hero-card ${S.unlocked.includes(h.id)?'selected':''}" style="--hero:${h.color}"><div class="portrait">${h.icon}<span>${h.level}</span></div><strong>${h.name}</strong><div class="meta">${h.role} · NV ${h.level}</div><div class="hp"><i style="width:${100*h.hp/(h.maxHp+b.hp)}%"></i></div><div class="stats"><span>⚔ ${Math.round((h.atk+b.attack)*(1+(h.level-1)*.12))}</span><span>♥ ${Math.round(h.maxHp+b.hp)}</span><span>◷ ${(h.rate+b.rate).toFixed(2)}</span></div><div class="gear-row">${['weapon','armor','charm'].map(s=>{let i=gear.find(x=>x.slot===s);return `<span class="gear-slot ${i?i.rarity:''}" title="${i?.name||'Slot vazio'}">${i?.icon||'·'}</span>`}).join('')}</div>${S.unlocked.includes(h.id)?`<button class="action" data-level="${h.id}">TREINAR · ${h.level*90} ☣</button>`:`<button class="action" data-unlock="${h.id}" ${S.scrap<h.cost?'disabled':''}>RECRUTAR · ${h.cost} ☣</button>`}</article>`}).join('')}</div>`;
else if(tab==='arsenal'){let selected=heroes.find(h=>h.id===S.selectedHero)||heroes[0],equippedIds=Object.values(S.equipped[selected.id]||{});p.innerHTML=`<div class="panel-head"><div><h2>ARSENAL</h2><p class="subtitle">${S.inventory.length}/60 itens · ${LootSystem.chanceLabel(S.lootPity)}</p></div><div class="survivor-select">${activeHeroes().map(h=>`<button data-select-hero="${h.id}" class="${selected.id===h.id?'on':''}">${h.icon} ${h.name}</button>`).join('')}</div></div><div class="loadout"><div><small>ARMA</small><b>${S.equipped[selected.id].weapon?'EQUIPADA':'VAZIA'}</b></div><div><small>PROTEÇÃO</small><b>${S.equipped[selected.id].armor?'EQUIPADA':'VAZIA'}</b></div><div><small>AMULETO</small><b>${S.equipped[selected.id].charm?'EQUIPADO':'VAZIO'}</b></div></div><div class="inventory">${S.inventory.length?S.inventory.map(i=>`<article class="item rarity-${i.rarity}"><span class="item-icon ${i.rarity}">${i.icon}</span><span class="item-info"><strong class="${i.rarity}">${i.name}</strong><em>${i.rarityLabel} · NV ${i.level} · QUALIDADE ${i.quality}%</em><small>${statText(i)}</small></span><span class="power"><b>${i.power}</b><small>PODER</small></span><div class="item-actions"><button class="action" data-equip="${i.id}">${equippedIds.includes(i.id)?'REMOVER':'EQUIPAR'}</button><button class="recycle" data-scrap="${i.id}" ${equippedIds.includes(i.id)?'disabled':''}>♻ ${i.salvage}</button></div></article>`).join(''):'<div class="empty-loot"><b>ARSENAL VAZIO</b><p>Infectados têm chance de derrubar equipamento. Um item é garantido após 12 eliminações sem saque.</p></div>'}</div>`}
else if(tab==='base')p.innerHTML=`<h2>ABRIGO 13</h2><div class="two-col"><div>${[['walls','Fortificações','Reduz o dano à base'],['turret','Torre automática','Dispara contra infectados'],['scavenger','Equipe de coleta','Aumenta a sucata recebida'],['medbay','Enfermaria','Regenera os sobreviventes']].map(([id,n,d])=>`<div class="mission"><h3>${n} · NV ${S.upgrades[id]}</h3><p>${d}</p><button class="action" data-upgrade="${id}">MELHORAR · ${(S.upgrades[id]+1)*350} ☣</button></div>`).join('')}</div><div><h3>INTEGRIDADE DO ABRIGO</h3><div class="bar"><i style="width:${100*S.baseHp/S.maxBaseHp}%"></i></div><p class="meta">${Math.ceil(S.baseHp)} / ${S.maxBaseHp}</p><button class="action" data-repair>REPARAR · ${Math.ceil((S.maxBaseHp-S.baseHp)*.25)} ☣</button></div></div>`;
else if(tab==='missions')p.innerHTML=`<h2>MISSÕES</h2>${[['kill50','Limpeza urbana',S.missions.kill50,50,150],['waves10','Aguente firme',S.missions.waves10,10,200],['boss1','Caça grande',S.missions.boss1,1,1]].map(([id,n,v,max,reward])=>`<div class="mission ${v>=max?'complete':''}"><h3>${n}</h3><div class="bar"><i style="width:${Math.min(100,v/max*100)}%"></i></div><p>${Math.min(v,max)} / ${max} · Recompensa: ${id==='boss1'?'1 ◆':reward+' ☣'}</p>${v>=max?`<button class="action" data-claim="${id}" data-reward="${reward}">RESGATAR</button>`:''}</div>`).join('')}`;
else p.innerHTML=`<h2>ARQUIVO DA QUARENTENA</h2><div class="two-col"><div><h3>ESTATÍSTICAS</h3><p>Infectados eliminados: <b>${S.kills}</b></p><p>Abominações abatidas: <b>${S.bosses}</b></p><p>Noite máxima: <b>${S.night}</b></p><p>Tempo em campo: <b>${Math.floor(S.playtime/60)} min</b></p></div><div><h3>CONQUISTAS (${S.achievements.length}/4)</h3>${['first','hundred','boss','night5'].map((id,i)=>`<p style="opacity:${S.achievements.includes(id)?1:.25}">☣ ${['Primeiro sangue','Exterminador','Quanto maior...','Cinco noites'][i]}</p>`).join('')}</div></div>`;bindPanel()}
function bindPanel(){document.querySelectorAll('[data-unlock]').forEach(b=>b.onclick=()=>{let h=heroes.find(x=>x.id===b.dataset.unlock);if(S.scrap>=h.cost){S.scrap-=h.cost;S.unlocked.push(h.id);S.selectedHero=h.id;toast(`${h.name} entrou no esquadrão`);renderPanel()}});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{let h=heroes.find(x=>x.id===b.dataset.level),c=h.level*90;if(S.scrap>=c){S.scrap-=c;h.level++;h.atk+=2;h.maxHp+=12;h.hp=h.maxHp;renderPanel()}});document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{let id=b.dataset.upgrade,c=(S.upgrades[id]+1)*350;if(S.scrap>=c){S.scrap-=c;S.upgrades[id]++;if(id==='walls'){S.maxBaseHp+=100;S.baseHp+=100}renderPanel()}});document.querySelectorAll('[data-select-hero]').forEach(b=>b.onclick=()=>{S.selectedHero=b.dataset.selectHero;renderPanel('arsenal')});document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{let item=S.inventory.find(i=>i.id===b.dataset.equip),set=S.equipped[S.selectedHero];if(!item||!set)return;if(set[item.slot]===item.id){set[item.slot]=null;toast(`${item.name} removido`)}else{set[item.slot]=item.id;toast(`${item.name} equipado`)}renderPanel('arsenal')});document.querySelectorAll('[data-scrap]').forEach(b=>b.onclick=()=>{let i=S.inventory.find(x=>String(x.id)===b.dataset.scrap);if(!i||Object.values(S.equipped).some(set=>Object.values(set).includes(i.id)))return;S.scrap+=Number(i.salvage||8);S.inventory=S.inventory.filter(x=>x!==i);toast(`Item reciclado · +${i.salvage||8} sucata`);renderPanel('arsenal')});document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{let id=b.dataset.claim;if(id==='boss1')S.cores++;else S.scrap+=+b.dataset.reward;S.missions[id]=0;renderPanel()});let r=document.querySelector('[data-repair]');if(r)r.onclick=()=>{let c=Math.ceil((S.maxBaseHp-S.baseHp)*.25);if(S.scrap>=c){S.scrap-=c;S.baseHp=S.maxBaseHp;renderPanel()}}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPanel(b.dataset.tab)});$('#expand').onclick=()=>{S.expanded=!S.expanded;document.body.className=S.expanded?'expanded':'compact';window.desktop?.mode(S.expanded?'expanded':'compact');$('#expand').textContent=S.expanded?'▾':'▣';if(S.expanded)renderPanel()};$('#pause').onclick=()=>{S.paused=!S.paused;$('#pause').textContent=S.paused?'▶':'Ⅱ'};$('#speed').onclick=()=>{S.speed=S.speed===1?2:S.speed===2?3:1;$('#speed').textContent=S.speed+'×'};$('#minimize').onclick=()=>window.desktop?.minimize();$('#close').onclick=()=>{save();window.desktop?.close()};
let away=Math.min(8*3600,Math.max(0,(Date.now()-S.lastSeen)/1000));if(away>60){let gain=Math.floor(away/10*(4+S.night));S.scrap+=gain;setTimeout(()=>toast(`Coleta offline: +${gain} sucata`),800)}
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;update(dt);draw();renderTop();autosave+=dt;if(autosave>10){save();autosave=0}requestAnimationFrame(loop)}startWave();renderPanel();requestAnimationFrame(loop);window.addEventListener('beforeunload',save);
})();
