(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LootSystem=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const RARITIES={common:{label:'Comum',color:'#aeb9b1',mult:1,affixes:0},uncommon:{label:'Incomum',color:'#71cf71',mult:1.3,affixes:1},rare:{label:'Raro',color:'#65b8ff',mult:1.75,affixes:2},epic:{label:'Épico',color:'#c383ff',mult:2.4,affixes:3},legendary:{label:'Lendário',color:'#ffb23e',mult:3.25,affixes:4}};
const BASES={weapon:[['Facão de Resgate','🗡'],['Carabina da Patrulha','⌁'],['Machado de Incêndio','🪓'],['Escopeta Quebra-Horda','▱']],armor:[['Colete Antimordida','🦺'],['Jaqueta de Motociclista','♜'],['Armadura da Tropa','▦'],['Traje Hazmat Reforçado','♙']],charm:[['Rádio de Emergência','◉'],['Insígnia do Último Turno','◆'],['Ampola Experimental','⚗'],['Relógio do Evacuado','◷']]};
const SPECIAL={maya:{label:'MAYA',bases:{weapon:[['Carabina de Precisão','🎯'],['Pistola Relâmpago','⚡']],armor:[['Colete da Batedora','🦺'],['Manto de Mobilidade','➤']],charm:[['Mira Neural','◉'],['Cronômetro Tático','◷']]},primary:{weapon:'attack',armor:'rate',charm:'crit'}},bruno:{label:'BRUNO',bases:{weapon:[['Marreta de Cerco','🔨'],['Escudo de Impacto','🛡']],armor:[['Couraça Antimordida','⬟'],['Armadura de Choque','▦']],charm:[['Placa de Fortitude','◆'],['Injetor de Adrenalina','♥']]},primary:{weapon:'hp',armor:'hp',charm:'hp'}},healer:{label:'MÉDICO',bases:{weapon:[['Pistola de Soro','💉'],['Bastão Cirúrgico','⚕']],armor:[['Jaleco de Trauma','🥼'],['Colete Paramédico','✚']],charm:[['Kit Médico de Campo','🩹'],['Desfibrilador Portátil','⚡']]},primary:{weapon:'healing',armor:'hp',charm:'healing'}},iris:{label:'IRIS',bases:{weapon:[['Lança-Chamas Compacto','🔥'],['Projetor de Napalm','♨']],armor:[['Traje de Bombeiro','🧯'],['Manto Antichamas','🔥']],charm:[['Catalisador Ígneo','☀'],['Ampola de Fósforo','♦']]},primary:{weapon:'attack',armor:'attack',charm:'crit'}}};
const PREFIX=['Remendado','Militar','Implacável','Contaminado','Veterano','Protocolo Zero'],SUFFIX=['da Quarentena','do Último Abrigo','da Lua Verde','do Extermínio','dos Esquecidos'];
const rand=(rng,a,b)=>a+rng()*(b-a),pick=(rng,a)=>a[Math.floor(rng()*a.length)];
function rarity(rng,pity=0,boss=false){if(boss)return pity>=15?'legendary':rng()<.35?'legendary':'epic';let roll=rng()+Math.min(.22,pity*.012);return roll>.985?'legendary':roll>.91?'epic':roll>.68?'rare':roll>.33?'uncommon':'common'}
function addStat(stats,key,scale,rng,strong=false){let value=key==='hp'?Math.round(rand(rng,strong?22:8,strong?38:16)*scale):key==='attack'?Math.round(rand(rng,strong?3.4:1.2,strong?5.5:3.1)*scale):key==='rate'?+rand(rng,strong?.03:.01,strong?.055:.028).toFixed(3):key==='crit'?+rand(rng,strong?.045:.015,strong?.075:.045).toFixed(3):key==='healing'?+rand(rng,strong?.09:.025,strong?.16:.07).toFixed(3):+rand(rng,.025,.065).toFixed(3);stats[key]+=value;return value}
function generate({level=1,pity=0,boss=false,rng=Math.random,profile}={}){let archetype=profile;if(!archetype){let roll=rng();archetype=roll<.16?'healer':roll<.32?'iris':null}const r=rarity(rng,pity,boss),meta=RARITIES[r],slot=pick(rng,Object.keys(BASES)),source=archetype?SPECIAL[archetype].bases:BASES,[base,icon]=pick(rng,source[slot]),quality=Math.round(rand(rng,72,100)),scale=(1+level*.14)*meta.mult*(quality/100),stats={attack:0,hp:0,rate:0,crit:0,scrap:0,healing:0};if(!archetype){if(slot==='weapon')stats.attack=Math.round(3.5*scale);if(slot==='armor')stats.hp=Math.round(24*scale);if(slot==='charm')stats.rate=+(0.025*scale).toFixed(3)}else addStat(stats,SPECIAL[archetype].primary[slot],scale,rng,true);if(archetype==='healer'&&slot!=='weapon')stats.rate+=+(.012*scale).toFixed(3);if(archetype==='iris'&&slot!=='armor')stats.attack+=Math.round(1.8*scale);let pool=['attack','hp','rate','crit','scrap','healing'],affixes=[];for(let i=0;i<meta.affixes;i++){let key=pool.splice(Math.floor(rng()*pool.length),1)[0],value=addStat(stats,key,scale,rng);affixes.push({key,value})}let name=(r==='common'?'':pick(rng,PREFIX)+' ')+base+(r==='epic'||r==='legendary'?' '+pick(rng,SUFFIX):''),power=Math.round(stats.attack*10+stats.hp*.7+stats.rate*260+stats.crit*180+stats.scrap*120+stats.healing*220);return{id:`item-${Date.now()}-${Math.floor(rng()*1e7)}`,name,base,icon,slot,rarity:r,rarityLabel:meta.label,quality,level,stats,affixes,archetype:archetype||'standard',archetypeLabel:archetype?SPECIAL[archetype].label:'GERAL',power,salvage:Math.max(8,Math.round(power*meta.mult*.4)),createdAt:Date.now()}}
function total(items=[]){return items.filter(Boolean).reduce((a,i)=>{Object.keys(a).forEach(k=>a[k]+=Number(i.stats?.[k]||0));return a},{attack:0,hp:0,rate:0,crit:0,scrap:0,healing:0})}
function chanceLabel(pity){return pity>=15?'Lendário garantido no próximo chefe':pity>=8?'Chance de raridade aumentada':'Proteção contra azar ativa'}
return{RARITIES,BASES,SPECIAL,generate,total,chanceLabel};
});
