(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PatchNotes=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const NOTES=[
 {version:'3.5.0',date:'07/08/2026',title:'Bestiário da Infecção',featured:true,sections:[['NOVOS INIMIGOS',['Criaturas voadoras atacam acima da horda','Incendiários causam dano ampliado','Explosivos se destroem causando grande impacto','Tóxicos, sanguessugas, congelantes e mutantes de fase','Blindados reduzem o dano recebido']],['MAPAS',['Cada região possui elenco próprio de criaturas','Novas espécies surgem gradualmente nas fases avançadas','Aparência, cores, tamanho e animações identificam cada ameaça']]]},
 {version:'3.4.0',date:'07/08/2026',title:'A Horda Contra-Ataca',featured:true,sections:[['DIFICULDADE',['Mais inimigos por onda e intervalos menores entre aparições','Vida, dano e velocidade escalam mais em mapas avançados','Sobrevivência, Loucura e Hardcore ficaram significativamente mais perigosos','Chefes possuem mais vida e causam mais dano']],['RISCO E FARM',['Derrota remove 25% da sucata','Farm AFK exige poder maior','Radar de farm atualizado para o novo balanceamento']]]},
 {version:'3.3.0',date:'07/08/2026',title:'Assistente de Equipamento',featured:true,sections:[['ARSENAL',['Recomendação dos melhores itens para cada herói','Melhor arma, proteção e amuleto exibidos no topo','Botão para equipar automaticamente o melhor conjunto','Itens recomendados recebem destaque visual']],['COMPARAÇÃO',['Percentual de melhoria comparado ao equipamento atual','Cálculo respeita os atributos importantes de cada classe']]]},
 {version:'3.2.0',date:'07/08/2026',title:'Meu Save Compartilhável',featured:true,sections:[['SAVE',['Salvamento automático de todo o progresso a cada 10 segundos','Exportação do progresso completo em arquivo .deadshift','Importação segura com validação de integridade','Backup automático do progresso atual antes de importar']],['PERFIL',['Nome personalizável para identificar o save','Resumo de recursos, heróis, itens e avanço no mapa']]]},
 {version:'3.1.0',date:'07/08/2026',title:'Radar Inteligente de Farm',featured:true,sections:[['MAPAS E FARM',['Radar recomenda automaticamente farm seguro, mais sucata, itens da classe escolhida e chefes','Cada mapa agora informa sua especialidade de saque','Seleção manual fixa o mapa e ativa a repetição automaticamente','Dificuldade e eficiência são calculadas com base no poder do esquadrão']],['LOOT',['Mapas especializados aumentam a chance de obter itens de DPS, Tank ou Cura']]]},
 {version:'3.0.1',date:'07/08/2026',title:'Relatório AFK Responsivo',sections:[['CORREÇÕES',['Relatório AFK expande a janela automaticamente','Botão de fechar permanece sempre visível','Tecla Esc fecha o relatório','Janela retorna ao tamanho anterior após fechar']]]},
 {version:'3.0.0',date:'07/08/2026',title:'Operação Renascimento',sections:[['NOVO',['Mapa interativo com seleção de fases liberadas','Auto-repetição com alvo de loot DPS, Tank ou Cura','Rede global de runas com caminhos e requisitos','Estação-Cubo com síntese e fabricação','Botão para fechar o relatório AFK']],['MELHORIAS',['Chefes concedem pontos de runa','Farm offline respeita a fase fixada','Interface de heróis e status reorganizada']]]},
 {version:'2.7.0',date:'07/08/2026',title:'Central de Atualizações',sections:[['NOVO',['Aba de patch notes dentro do jogo','Histórico organizado por versão e categoria','Monitoramento automático diário do projeto']],['MELHORIAS',['Erros do atualizador agora aparecem de forma amigável','Compatibilidade preservada com saves anteriores']]]},
 {version:'2.6.1',date:'07/08/2026',title:'Correção do Atualizador',sections:[['CORREÇÕES',['Removida a mensagem técnica extensa quando o GitHub está indisponível','Preparação dos artefatos para atualização incremental']]]},
 {version:'2.6.0',date:'07/08/2026',title:'A Campanha dos Cinco Mapas',sections:[['NOVO',['Cinco mapas com dez níveis cada','Chefes e famílias de inimigos por região','Modos Normal, Sobrevivência, Loucura e Hardcore','Laboratório Criogênico original']],['BALANCEAMENTO',['Força, velocidade, tamanho das hordas e recompensas escalam por nível e modo','Hardcore continua em ciclos infinitos']]]},
 {version:'2.5.0',date:'07/08/2026',title:'Arsenal Especializado',sections:[['NOVO',['Filtros DPS, Tank e Cura','Etiquetas de função nos equipamentos','Novo atributo Poder de Cura']],['MELHORIAS',['Poder de Cura fortalece a habilidade do Yuri','Contadores por categoria no arsenal']]]},
 {version:'2.4.0',date:'07/08/2026',title:'Companheiros do Fim',sections:[['NOVO',['Rex, Luna, Casco e Nox','Pets visíveis no combate','Treinamento de companheiros até o nível 10','Bônus de pets aplicados ao combate e farm AFK']]]},
 {version:'2.3.0',date:'07/08/2026',title:'Equipamento Inteligente',sections:[['NOVO',['Comparação com o item equipado','Recomendação específica para cada personagem','Atualizador automático e instalador do Windows']]]},
 {version:'2.2.0',date:'07/08/2026',title:'Farm AFK',sections:[['NOVO',['Progresso offline limitado a oito horas','Relatório de eliminações, sucata, experiência, itens e baús']]]}
];
return{NOTES};
});
