(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Progression=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const HEROES={
 maya:{role:'Vanguarda',identity:'Dano + velocidade',abilities:[{id:'burst',name:'Rajada Cinética',icon:'⌁',cooldown:8,desc:'Dispara 6 tiros no alvo mais próximo.'},{id:'dash',name:'Passo Fantasma',icon:'»',cooldown:14,desc:'Dobra a velocidade e o crítico por 6s.'},{id:'mark',name:'Marca do Caçador',icon:'◎',cooldown:20,desc:'Marca inimigos para receberem +40% de dano.'}],tree:[['m_atk','Munição perfurante','attack',.08],['m_speed','Dedos rápidos','rate',.06],['m_crit','Ponto vital','crit',.025],['m_elite','Predadora alfa','eliteDamage',.12],['m_master','Sem descanso','cooldown',.08]]},
 bruno:{role:'Guardião',identity:'Tanque + controle',abilities:[{id:'taunt',name:'Última Barreira',icon:'▣',cooldown:12,desc:'Provoca a horda e reduz o dano à base.'},{id:'slam',name:'Impacto Sísmico',icon:'◇',cooldown:16,desc:'Atordoa todos os inimigos próximos.'},{id:'fortify',name:'Fortificar',icon:'⬟',cooldown:24,desc:'Cria um escudo para todo o esquadrão.'}],tree:[['b_hp','Placas extras','hp',.12],['b_armor','Fibra balística','armor',.08],['b_block','Escudo angular','block',.04],['b_thorns','Retaliação','thorns',.12],['b_master','Imóvel','baseGuard',.15]]},
 yuri:{role:'Socorrista',identity:'Cura + suporte',abilities:[{id:'heal',name:'Pulso Médico',icon:'✚',cooldown:10,desc:'Cura o sobrevivente mais ferido.'},{id:'stim',name:'Estimulante',icon:'⚕',cooldown:18,desc:'Aumenta a velocidade de toda a equipe.'},{id:'revive',name:'Sem Baixas',icon:'♢',cooldown:35,desc:'Recupera aliados abatidos e restaura vida.'}],tree:[['y_heal','Triagem','healing',.12],['y_haste','Adrenalina','teamRate',.035],['y_shield','Barreira química','shield',.08],['y_supply','Busca clínica','loot',.06],['y_master','Juramento','regen',.15]]},
 iris:{role:'Controladora',identity:'Área + queimadura',abilities:[{id:'molotov',name:'Chuva de Fogo',icon:'🔥',cooldown:11,desc:'Incendeia uma grande área por 8s.'},{id:'mine',name:'Mina Criogênica',icon:'❄',cooldown:17,desc:'Explode, causa dano e reduz velocidade.'},{id:'inferno',name:'Protocolo Inferno',icon:'☄',cooldown:28,desc:'Sequência de explosões em toda a tela.'}],tree:[['i_area','Mistura volátil','area',.1],['i_burn','Fósforo branco','burn',.12],['i_slow','Agente térmico','slow',.08],['i_chain','Reação em cadeia','chain',.05],['i_master','Terra arrasada','execute',.06]]},
 vega:{role:'Atiradora',identity:'Chefe + crítico',abilities:[{id:'snipe',name:'Tiro Perfeito',icon:'🎯',cooldown:10,desc:'Causa dano extremo ao inimigo mais resistente.'},{id:'focus',name:'Respiração Zero',icon:'◎',cooldown:17,desc:'Aumenta crítico e dano da equipe.'},{id:'pierce',name:'Linha de Morte',icon:'➤',cooldown:27,desc:'Perfura toda a horda.'}],tree:[['v_atk','Munição match','attack',.1],['v_crit','Ótica neural','crit',.035],['v_elite','Caçadora de alfa','eliteDamage',.15],['v_rate','Ferrolho leve','rate',.04],['v_master','Um disparo','execute',.08]]},
 atlas:{role:'Bastião',identity:'Escudo + provocação',abilities:[{id:'bulwark',name:'Linha Inquebrável',icon:'▣',cooldown:11,desc:'Reduz fortemente todo dano recebido.'},{id:'ram',name:'Avanço de Escudo',icon:'▶',cooldown:16,desc:'Atordoa a linha de frente.'},{id:'aegis',name:'Égide',icon:'⬢',cooldown:28,desc:'Restaura a base e protege a equipe.'}],tree:[['a_hp','Placas industriais','hp',.15],['a_armor','Absorção','armor',.1],['a_block','Postura fechada','block',.06],['a_base','Defensor do abrigo','baseGuard',.16],['a_master','Não passarão','regen',.12]]},
 luna:{role:'Doutora',identity:'Cura + prevenção',abilities:[{id:'vaccine',name:'Vacina de Campo',icon:'⚕',cooldown:9,desc:'Cura e concede regeneração.'},{id:'cleanse',name:'Descontaminação',icon:'✚',cooldown:16,desc:'Remove efeitos e cura o grupo.'},{id:'miracle',name:'Protocolo Milagre',icon:'✦',cooldown:32,desc:'Revive e protege toda a equipe.'}],tree:[['l_heal','Dose concentrada','healing',.15],['l_rate','Aplicação rápida','rate',.04],['l_regen','Imunidade','regen',.18],['l_supply','Farmácia móvel','loot',.08],['l_master','Sem perdas','shield',.12]]},
 knox:{role:'Engenheiro',identity:'Drone + farm',abilities:[{id:'turret',name:'Drone Sentinela',icon:'⚙',cooldown:10,desc:'O drone dispara contra quatro inimigos.'},{id:'overclock',name:'Overclock',icon:'⌁',cooldown:18,desc:'Acelera toda a equipe.'},{id:'barrage',name:'Barragem Mecânica',icon:'▰',cooldown:29,desc:'Bombardeia todos os inimigos.'}],tree:[['k_atk','Calibre maior','attack',.07],['k_rate','Servo rápido','rate',.055],['k_scrap','Reciclagem','scrap',.05],['k_turret','Engenharia reversa','eliteDamage',.1],['k_master','Automação','cooldown',.08]]},
 sombra:{role:'Infiltradora',identity:'Velocidade + execução',abilities:[{id:'execute',name:'Execução',icon:'◐',cooldown:8,desc:'Finaliza o inimigo mais ferido.'},{id:'vanish',name:'Desaparecer',icon:'◇',cooldown:15,desc:'Ganha velocidade e crítico.'},{id:'assassinate',name:'Noite Sem Fim',icon:'✕',cooldown:25,desc:'Ataca vários alvos em sequência.'}],tree:[['s_crit','Ponto cego','crit',.04],['s_rate','Gatilho duplo','rate',.07],['s_atk','Munição negra','attack',.07],['s_exec','Sem testemunhas','execute',.1],['s_master','Fantasma','cooldown',.1]]},
 raio:{role:'Choque',identity:'Cadência + corrente',abilities:[{id:'surge',name:'Sobrecarga',icon:'ϟ',cooldown:9,desc:'Dano elétrico em cadeia.'},{id:'haste',name:'Impulso Voltaico',icon:'»',cooldown:15,desc:'Aumenta muito a velocidade.'},{id:'storm',name:'Tempestade',icon:'☇',cooldown:26,desc:'Eletrifica toda a tela.'}],tree:[['r_rate','Capacitor','rate',.075],['r_atk','Alta tensão','attack',.065],['r_crit','Arco crítico','crit',.025],['r_chain','Condutor','chain',.08],['r_master','Carga infinita','cooldown',.08]]},
 hana:{role:'Ronin',identity:'Dano + contra-ataque',abilities:[{id:'slash',name:'Corte Relâmpago',icon:'⚔',cooldown:9,desc:'Golpe devastador na linha de frente.'},{id:'stance',name:'Postura Carmesim',icon:'◆',cooldown:16,desc:'Aumenta dano e bloqueio.'},{id:'bladestorm',name:'Mil Cortes',icon:'※',cooldown:27,desc:'Corta todos os inimigos.'}],tree:[['h_atk','Lâmina afiada','attack',.11],['h_crit','Iaijutsu','crit',.03],['h_block','Aparar','block',.04],['h_elite','Duelo','eliteDamage',.14],['h_master','Último corte','execute',.08]]},
 muralha:{role:'Artilheira',identity:'Supressão + resistência',abilities:[{id:'suppress',name:'Fogo de Supressão',icon:'▰',cooldown:10,desc:'Metralha e desacelera a horda.'},{id:'brace',name:'Ancorar',icon:'⬟',cooldown:17,desc:'Ganha defesa e cadência.'},{id:'minigun',name:'Chuva de Chumbo',icon:'▥',cooldown:28,desc:'Rajada massiva em área.'}],tree:[['u_rate','Alimentação dupla','rate',.065],['u_hp','Armadura pesada','hp',.1],['u_atk','Munição grossa','attack',.07],['u_slow','Supressão','slow',.1],['u_master','Sem recuar','armor',.08]]},
 echo:{role:'Bioquímico',identity:'Debuff + controle',abilities:[{id:'plague',name:'Nuvem Mutagênica',icon:'⌬',cooldown:10,desc:'Marca e enfraquece a horda.'},{id:'freeze',name:'Composto Criônico',icon:'❄',cooldown:17,desc:'Congela os inimigos próximos.'},{id:'collapse',name:'Colapso Celular',icon:'☣',cooldown:28,desc:'Amplifica dano contra todos.'}],tree:[['e_area','Difusor','area',.1],['e_slow','Criogenia','slow',.1],['e_mark','Patógeno frágil','eliteDamage',.12],['e_loot','Amostras','scrap',.04],['e_master','Reação crítica','crit',.025]]},
 padre:{role:'Capelão',identity:'Suporte + sobrevivência',abilities:[{id:'blessing',name:'Último Rito',icon:'✦',cooldown:11,desc:'Cura e fortalece a equipe.'},{id:'judgment',name:'Julgamento',icon:'☼',cooldown:18,desc:'Dano sagrado contra elites.'},{id:'sanctuary',name:'Santuário',icon:'✚',cooldown:31,desc:'Revive aliados e repara a base.'}],tree:[['p_hp','Fé de ferro','hp',.09],['p_heal','Unção','healing',.1],['p_atk','Julgamento','attack',.06],['p_regen','Esperança','regen',.12],['p_master','Milagre','shield',.1]]}
};
const EXPEDITION=[['chestRate','Mais baús','Chance de baú +5%',1],['chestQuality','Fechaduras antigas','Qualidade dos itens +4%',1],['damage','Treino de campo','Dano da equipe +5%',1],['speed','Marcha forçada','Velocidade de ataque +4%',1],['offline','Turno automático','Recompensa offline +10%',1],['rare','Olho de sucateiro','Chance rara +3%',2],['bossChest','Troféu da abominação','Chefes dão baú lendário',3]];
function ensure(s){s.skillPoints=s.skillPoints||{};s.heroTalents=s.heroTalents||{};s.expedition=s.expedition||{};s.expeditionPoints=Number(s.expeditionPoints||0);s.chests=s.chests||{field:0,military:0,outbreak:0};Object.keys(HEROES).forEach(id=>{s.skillPoints[id]=Number(s.skillPoints[id]||0);s.heroTalents[id]=s.heroTalents[id]||{}});return s}
function heroBonuses(s,id){ensure(s);let out={};for(const [node,,,value] of HEROES[id].tree){let rank=Number(s.heroTalents[id][node]||0),stat=HEROES[id].tree.find(x=>x[0]===node)[2];out[stat]=(out[stat]||0)+rank*value}return out}
function expeditionBonuses(s){ensure(s);let o={};for(const [id,,,cost] of EXPEDITION)o[id]=Number(s.expedition[id]||0)*(id==='offline'?.1:id==='rare'?.03:id==='chestQuality'?.04:id==='chestRate'||id==='damage'?.05:id==='speed'?.04:1);return o}
function buyHero(s,hero,node){ensure(s);let def=HEROES[hero]?.tree.find(n=>n[0]===node);if(!def)return false;let rank=Number(s.heroTalents[hero][node]||0),cost=rank+1;if(rank>=5||s.skillPoints[hero]<cost)return false;s.skillPoints[hero]-=cost;s.heroTalents[hero][node]=rank+1;return true}
function buyExpedition(s,node){ensure(s);let def=EXPEDITION.find(n=>n[0]===node);if(!def)return false;let rank=Number(s.expedition[node]||0),cost=def[3]+rank;if(rank>=5||s.expeditionPoints<cost)return false;s.expeditionPoints-=cost;s.expedition[node]=rank+1;return true}
return{HEROES,EXPEDITION,ensure,heroBonuses,expeditionBonuses,buyHero,buyExpedition};
});
