(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Progression=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const HEROES={
 maya:{role:'Vanguarda',identity:'Dano + velocidade',abilities:[{id:'burst',name:'Rajada Cinética',icon:'⌁',cooldown:8,desc:'Dispara 6 tiros no alvo mais próximo.'},{id:'dash',name:'Passo Fantasma',icon:'»',cooldown:14,desc:'Dobra a velocidade e o crítico por 6s.'},{id:'mark',name:'Marca do Caçador',icon:'◎',cooldown:20,desc:'Marca inimigos para receberem +40% de dano.'}],tree:[['m_atk','Munição perfurante','attack',.08],['m_speed','Dedos rápidos','rate',.06],['m_crit','Ponto vital','crit',.025],['m_elite','Predadora alfa','eliteDamage',.12],['m_master','Sem descanso','cooldown',.08]]},
 bruno:{role:'Guardião',identity:'Tanque + controle',abilities:[{id:'taunt',name:'Última Barreira',icon:'▣',cooldown:12,desc:'Provoca a horda e reduz o dano à base.'},{id:'slam',name:'Impacto Sísmico',icon:'◇',cooldown:16,desc:'Atordoa todos os inimigos próximos.'},{id:'fortify',name:'Fortificar',icon:'⬟',cooldown:24,desc:'Cria um escudo para todo o esquadrão.'}],tree:[['b_hp','Placas extras','hp',.12],['b_armor','Fibra balística','armor',.08],['b_block','Escudo angular','block',.04],['b_thorns','Retaliação','thorns',.12],['b_master','Imóvel','baseGuard',.15]]},
 yuri:{role:'Socorrista',identity:'Cura + suporte',abilities:[{id:'heal',name:'Pulso Médico',icon:'✚',cooldown:10,desc:'Cura o sobrevivente mais ferido.'},{id:'stim',name:'Estimulante',icon:'⚕',cooldown:18,desc:'Aumenta a velocidade de toda a equipe.'},{id:'revive',name:'Sem Baixas',icon:'♢',cooldown:35,desc:'Recupera aliados abatidos e restaura vida.'}],tree:[['y_heal','Triagem','healing',.12],['y_haste','Adrenalina','teamRate',.035],['y_shield','Barreira química','shield',.08],['y_supply','Busca clínica','loot',.06],['y_master','Juramento','regen',.15]]},
 iris:{role:'Controladora',identity:'Área + queimadura',abilities:[{id:'molotov',name:'Chuva de Fogo',icon:'🔥',cooldown:11,desc:'Incendeia uma grande área por 8s.'},{id:'mine',name:'Mina Criogênica',icon:'❄',cooldown:17,desc:'Explode, causa dano e reduz velocidade.'},{id:'inferno',name:'Protocolo Inferno',icon:'☄',cooldown:28,desc:'Sequência de explosões em toda a tela.'}],tree:[['i_area','Mistura volátil','area',.1],['i_burn','Fósforo branco','burn',.12],['i_slow','Agente térmico','slow',.08],['i_chain','Reação em cadeia','chain',.05],['i_master','Terra arrasada','execute',.06]]}
};
const EXPEDITION=[['chestRate','Mais baús','Chance de baú +5%',1],['chestQuality','Fechaduras antigas','Qualidade dos itens +4%',1],['damage','Treino de campo','Dano da equipe +5%',1],['speed','Marcha forçada','Velocidade de ataque +4%',1],['offline','Turno automático','Recompensa offline +10%',1],['rare','Olho de sucateiro','Chance rara +3%',2],['bossChest','Troféu da abominação','Chefes dão baú lendário',3]];
function ensure(s){s.skillPoints=s.skillPoints||{};s.heroTalents=s.heroTalents||{};s.expedition=s.expedition||{};s.expeditionPoints=Number(s.expeditionPoints||0);s.chests=s.chests||{field:0,military:0,outbreak:0};Object.keys(HEROES).forEach(id=>{s.skillPoints[id]=Number(s.skillPoints[id]||0);s.heroTalents[id]=s.heroTalents[id]||{}});return s}
function heroBonuses(s,id){ensure(s);let out={};for(const [node,,,value] of HEROES[id].tree){let rank=Number(s.heroTalents[id][node]||0),stat=HEROES[id].tree.find(x=>x[0]===node)[2];out[stat]=(out[stat]||0)+rank*value}return out}
function expeditionBonuses(s){ensure(s);let o={};for(const [id,,,cost] of EXPEDITION)o[id]=Number(s.expedition[id]||0)*(id==='offline'?.1:id==='rare'?.03:id==='chestQuality'?.04:id==='chestRate'||id==='damage'?.05:id==='speed'?.04:1);return o}
function buyHero(s,hero,node){ensure(s);let def=HEROES[hero]?.tree.find(n=>n[0]===node);if(!def)return false;let rank=Number(s.heroTalents[hero][node]||0),cost=rank+1;if(rank>=5||s.skillPoints[hero]<cost)return false;s.skillPoints[hero]-=cost;s.heroTalents[hero][node]=rank+1;return true}
function buyExpedition(s,node){ensure(s);let def=EXPEDITION.find(n=>n[0]===node);if(!def)return false;let rank=Number(s.expedition[node]||0),cost=def[3]+rank;if(rank>=5||s.expeditionPoints<cost)return false;s.expeditionPoints-=cost;s.expedition[node]=rank+1;return true}
return{HEROES,EXPEDITION,ensure,heroBonuses,expeditionBonuses,buyHero,buyExpedition};
});
